# Generated by Django 2.0.6 on 2018-06-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
